apiVersion: branch.github.upbound.io/v1alpha1
kind: Branch
metadata:
  name: hello-provider-github
spec:
  forProvider:
    repositoryRef:
      name: hello-provider-github
  providerConfigRef:
    name: default
