apiVersion: actions.github.upbound.io/v1alpha1
kind: OrganizationSecret
metadata:
  annotations:
    meta.upbound.io/example-id: actions/v1alpha1/organizationsecret
  labels:
    testing.upbound.io/example-name: example_secret
  name: example-secret
spec:
  forProvider:
    plaintextValueSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    secretName: example_secret_name
    visibility: private
